name             'my_app'
maintainer       'IIII'
maintainer_email 'chris.d.cunha@gmail.com'
license          'All rights reserved'
description      'Installs/Configures my_app'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'apache2'
depends 'database'
depends 'git'